const creepConfiguration = {
    components:{
        "harvester":{move:3,work:5,carry:1},
        "transferer":{move:10,carry:10},
        "weak_transferer":{move:5,carry:5},
        "upgrader":{move:6,work:10,carry:2},
        "worker":{work:5,carry:15,move:10},
        "repairer":{work:5,carry:3,move:4},
        "defender":{move:23,"ranged_attack":5,attack:15,heal:5},
        "defender_reserved":{move:12,"ranged_attack":5,attack:5,heal:2},
        "defender_observed":{tough:5,move:10,"ranged_attack":25,heal:10},
        "defender_observed_servant":{attack:5,move:25,"ranged_attack":15,heal:5},
        "attacker":{move:25,attack:25},
        "healer":{move:16,heal:16},
        "claimer":{move:2,claim:2},
        "traveler":{move:1},
        "attacker_invader_low":{tough:4,"ranged_attack":12,move:5,heal:4},
    },
    boosts:{
        "transferer":{
            "remoteTransfer":["KH","KH2O","XKH2O"],
            "remotePickUper":[],
            "pureTransfer":["KH","KH2O","XKH2O"],
            "remoteHarvest":["KH"],
        },
        "repairer":{
            "pureRepairer":["LH","LH2O","XLH2O"],
        },
        "attacker":{
            "Attack":["UH","UH2O","XH2O"],
        },
        "healer":{
            "Attack":["LO","LHO2","XLHO2"],
        },
        "upgrader":{
            "pureUpgrader":["GH","GH2O","XGH2O"],
        },
        "worker":{
            "pureWorker":["KH"]
        },
        "defender_observed":{
            "Defend_observed":["LO","LHO2","XLHO2","GO","GHO2","XGHO2","XZHO2","ZHO2","ZO","UH","UH2O","XUH2O","XKHO2"]
        },
        "attacker_invader_low":{
            "AttackInvaderLow":["XUH2O","XZHO2","XGHO2","XLHO2","XKHO2"]
        }
    },
    groupAcceptedTask:{
        // PRIMARY KEY PRINCIPLE
        "remoteHarvest":{"harvester":["harvest-remote"],"transferer":["-transfer-remote"]},
        "powerHarvest":{"attacker":["attack-harvest"],"healer":["-attack-heal"]},
        "localHarvest":{"harvester":["harvest-local"]},
        "pureTransfer":{"transferer":["transfer-core","transfer-defense","pickup-local","transfer-advanced","transfer-basic"]},
        "centralTransfer":{"weak_transferer":["transfer-bbasic","transfer-basic"]},
        "pureWorker":{"worker":["build-local","build-remote","*transfer-core","*repair-local","*upgrade"]},
        "pureRepairer":{"repairer":["repair-local","*transfer-core","*upgrade"]},
        "remoteRepairer":{"repairer":["repair-remote","build-remote"]},
        "remoteTransfer":{"transferer":["transfer-aid"]},
        "remotePickUper":{"transferer":["transfer-remote","pickup-remote"]},
        "pureUpgrader":{"upgrader":["upgrade"]},
        "Defend":{"defender":["defend-local|central|observed"]},
        "Defend_reserved":{"defender_reserved":["defend-reserved"]},
        "Defend_observed":{"defender_observed":["defend-observed"]},
        "Attack":{"attacker":["attack-attack"],"healer":["-attack-heal"]},
        "Claim":{"claimer":["attack-claim"]},
        "Travel":{"traveler":["travel"]},
        "AttackInvaderLow":{"attacker_invader_low":["attack-invade"]},
    },
    groupSpawnConfig:{
        "powerHarvest":{"healer":2},
        "Defend_observed":{"defender_observed":1},
    }
}
module.exports = creepConfiguration