const labConfiguration = {
    leastRefillAmount:5,
    leastTransferAmount:50,
    "W22N25":{
        mode:"default",
        allowedCompounds:[],
        reverse:[],
        default:[],
        focus:undefined,
        clear:undefined
    },
    "W23N25":{
        mode:"default",
        allowedCompounds:[],
        reverse:[],
        default:[],
        focus:undefined,
        clear:undefined
    },
    "W21N24":{
        mode:"default",
        allowedCompounds:[],
        reverse:[],
        default:[],
        focus:undefined,
        clear:undefined
    },
    "W19N22":{
        mode:"default",
        allowedCompounds:[],
        reverse:[],
        default:[],
        focus:undefined,
        clear:undefined
    }
}
module.exports = labConfiguration